# Render Blueprint for Transit TV - use this to jumpstart an instance on Render
services:
  - type: web
    name: Transit-TV
    runtime: docker
    repo: https://github.com/jasonad123/Transit-TV
    envVars:
      - key: TRANSIT_API_KEY
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: ENABLE_SERVER_CACHE
        sync: false
      - key: PORT
        value: 8080
      - key: NODE_ENV
        value: production
    dockerContext: .
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    autoDeployTrigger: commit
    buildFilter:
      paths:
        - server/**
        - svelte-app/**
        - package.json
        - svelte-app/package.json
      ignoredPaths:
        - docs/**
        - README.md
